version: '2'
services:
  signature_pad:
    build:
      context: ./
      dockerfile: app.dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: ng build signature-pad --watch
    networks:
      - default
  pad.bluemoonformsdev.com:
    build:
      context: ./
      dockerfile: app.dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: ng serve --host pad.bluemoonformsdev.com --disable-host-check
    ports:
      - "4200"
    networks:
      - default
networks:
  default:
    external: true
    name: dev-network
