version: '2'
services:
  signature_pad:
    build:
      context: ./
      dockerfile: app.dockerfile
    volumes:
      - ./angular.json:/usr/src/app/angular.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./projects/signature-pad:/usr/src/app/projects/signature-pad
      - dist_output:/usr/src/app/dist/signature-pad
      - /usr/src/app/node_modules
    command: ng build signature-pad --watch
    networks:
      - default
  pad.bluemoonformsdev.com:
    build:
      context: ./
      dockerfile: app.dockerfile
    volumes:
      - ./angular.json:/usr/src/app/angular.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./projects/debug-viewer:/usr/src/app/projects/debug-viewer
      - dist_output:/usr/src/app/dist/signature-pad
      - /usr/src/app/node_modules
    command: ng serve --host pad.bluemoonformsdev.com --disable-host-check
    ports:
      - "4200"
    networks:
      - default
networks:
  default:
    external: true
    name: dev-network
volumes:
  dist_output:
    external: false
